// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAytEDOL5D7BpiFCHB6U1oMddV_rspgpRo',
    appId: '1:386806053414:web:692f71c793573e954984e7',
    messagingSenderId: '386806053414',
    projectId: 'tubes-ppb-b5449',
    authDomain: 'tubes-ppb-b5449.firebaseapp.com',
    storageBucket: 'tubes-ppb-b5449.appspot.com',
    measurementId: 'G-G23ZFRE9L2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKzBGfdmvbD5_C9lCEvYV87k5vE9T8SlI',
    appId: '1:386806053414:android:3cc04db1f06ec6554984e7',
    messagingSenderId: '386806053414',
    projectId: 'tubes-ppb-b5449',
    storageBucket: 'tubes-ppb-b5449.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9Heg_H555rCK_lzNWmsKUvmWXNZi2jRI',
    appId: '1:386806053414:ios:438dbc5372a5aed44984e7',
    messagingSenderId: '386806053414',
    projectId: 'tubes-ppb-b5449',
    storageBucket: 'tubes-ppb-b5449.appspot.com',
    iosClientId: '386806053414-h5vh6q2j69b8e6hranbb9qvfqu9ofnek.apps.googleusercontent.com',
    iosBundleId: 'com.example.myAppFlutter1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9Heg_H555rCK_lzNWmsKUvmWXNZi2jRI',
    appId: '1:386806053414:ios:1eec05bed6233cde4984e7',
    messagingSenderId: '386806053414',
    projectId: 'tubes-ppb-b5449',
    storageBucket: 'tubes-ppb-b5449.appspot.com',
    iosClientId: '386806053414-cpn0iueon77u4luo3tjqg3g5kn91mhk5.apps.googleusercontent.com',
    iosBundleId: 'com.example.myAppFlutter1.RunnerTests',
  );
}
